@startuml Nivel2
!include https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Container.puml

title Diagrama de Contêineres - Sistema de Gerenciamento de Oficina Mecânica

Person(Funcionario, "Funcionário", "Funcionário da oficina mecânica")
Person(Admin, "Administrador", "Administrador do sistema")
Person(Cliente, "Cliente", "Solicitante do serviço")

System_Boundary(Sistemaoficina, "Sistema de Gerenciamento de Oficina Mecânica") {
  Container(FrontendWeb, "Frontend Web", "React + Vite + Tailwind CSS", "Interface web para homepage, login e operações CRUD")
  Container(BackendAPI, "Backend API", "Node.js + Express", "API REST responsável por autenticação, regras de negócio e controle de acesso")
  ContainerDb(Database, "Banco de Dados", "MongoDB", "Armazena usuários, clientes e veículos")
}

Rel(Cliente, FrontendWeb, "Consulta informações e status do veículo", "HTTPS")
Rel(Funcionario, FrontendWeb, "Utiliza funcionalidades do sistema", "HTTPS")
Rel(Admin, FrontendWeb, "Administra usuários e permissões", "HTTPS")
Rel(FrontendWeb, BackendAPI, "Requisições REST", "JSON / HTTPS")
Rel(BackendAPI, Database, "Persistência de dados", "Mongoose / TCP")

LAYOUT_WITH_LEGEND()
@enduml
