@startuml Nivel1
!include https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Context.puml

title Contexto - Gerenciamento de Oficina Mecânica

Person(Funcionario, "Funcionário", "Funcionário da oficina mecânica responsável pelo cadastro e controle de veículos")
Person(Admin, "Administrador", "Administrador do sistema com acesso total")
Person(Cliente, "Cliente", "Solicitante do serviço e proprietário do veículo")

System(Sistemaoficina, "Sistema de Gerenciamento de Oficina Mecânica", "Sistema web para controle de veículos em reparo, autenticação por CPF/senha e controle de acesso por perfis")

Rel(Funcionario, Sistemaoficina, "Gerencia veículos (cadastro, atualização de status, exclusão)", "Web")
Rel(Admin, Sistemaoficina, "Administra usuários e veículos", "Web")
Rel(Cliente, Sistemaoficina, "Fornece dados do cliente e do veículo e consulta status", "Web")

LAYOUT_WITH_LEGEND()
@enduml
